### ISSUE TITLE
OpenSSL Library name in Windows

### ISSUE THREAD

**Issue by kemege** [cowboy-coders/nim-openssl-evp#2]
The OpenSSL dynamic libraries are `libeay32.dll` and `ssleay32.dll` for Windows, corresponding to `libcrypto.so` and `libssl.so` for Linux.

So for Windows, cryptodll shoud be "libeay32.dll".

**Comment by jovial** [comment]
Thanks. I don't suppose you can test the code I just pushed to nim-openssl-evp/fix/windows?

**Comment by kemege** [comment]
The example code runs without problem now. Thank you.
